apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: qstart
  namespace: default
spec:
  interval: 1m0s
  prune: true
  path: ./
  sourceRef:
    kind: GitRepository
    name: qstart
  targetNamespace: default
