apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kustomize-quarkus
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  path: ./kubernetes/overlays/development  # dit pad moet correct zijn
  sourceRef:
    kind: GitRepository
    name: kustomize-quarkus
  targetNamespace: default
